name: CI
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build image from Dockerfile.dev
        run: docker build -t jwandekoken/test-react-app -f Dockerfile.dev .

      - name: log docker images
        run: docker images

      - name: run test-react-app image with 'npm run test' command
        env:
          CI: true
        run: docker run jwandekoken/test-react-app npm run test
